### ISSUE TITLE
'Within Bone Location' - 'Multiple surfaces': Suggested change of name

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#23]
The Phaleron Paleopathology Scoring Key (Version 17 September 2021) defines the categorical data item 'Within Bone Location'. The category designated by the numerical code 13 is named 'Multiple surfaces'.

The category name might be misleading as the other categories all describe aspects (e.g. 'medial', 'distal', 'superior') of skeletal elements rather than surfaces.

I assume that the category 'Multiple surfaces' should be chosen in cases where more than one of the other categories are applicable. For example, if the anterior and lateral aspects of the outer surface of the proximal third of the diaphysis of a left humerus (L Humerus: P1/3) are affected by some condition, this cannot be expressed with any of the categories 1 to 12. This is because several aspects are involved. Still, the observation is made on just one surface.

Following my argumentation for #22, I suggest to rename the category to 'Multiple aspects'.

@JEB13, Eleanna, @HannahLiedl, @JessHotaling and @hayesleigh, please discuss and post results here.

**Comment by cuboideum** [comment]
It should be noted that, technically, multiple categorical labels can be selected for the same instance of a categorical measurement datum. Is the category 'Multiple surfaces' still needed, given this fact? The answer should be found considering the requirements of data analysis.

**Comment by JEB13** [comment]
I see what you are saying.  So long as there is the option to select a number of aspects for the type of observation, e.g, bone addition, periostosis, then the category wouldn't me needed.  Others?

**Comment by HannahLiedl** [comment]
We introduced "multiple surfaces" as an option because we decided to not put more than one option in a field in the spreadsheet. If we can choose more than one aspect in the database, this issue should be resolved, I believe.

**Comment by JEB13** [comment]
Yes, resolved, I think?

**Comment by cuboideum** [comment]
Fixed in commit RDFBones/Phaleron-Pathologies@46cdf8661327e01750720922e653340898c73bb0.

**Comment by sacheever** [comment]
Hi all, Sylvia here. Anticipating a potential problem here in that, while in an ideal world observers will have specified what they mean by entering the ‘multiple surfaces’ option into the excel spreadsheet, there is a possibility that a) the pathological observation was not significant enough to be described in enough detail in the notes/report, b) the original observer forgot to specify, or c) given some of the recent events, the report or notes are not up-to-date or are lost altogether. Especially because we are having different data editors retroactively enter data, and the data was collected by many different observers, and sometimes re-collected, this may be something we encounter. I have certainly come across many instances where reports do not reference everything coded in the data sheets, or where the data sheets post-date the report we have on file. I feel we should have an option for  ‘Multiple Aspects (unspecified)’ or even just ‘unspecified’ in rare instances where this may be the case, so that we do not lose those pathological observations entirely for lack of a specific aspect to enter.

Side Note: If there is desire for this database to be relevant to/useable by other bioarchaeological projects, having an ‘Unspecified’ option or a ‘Multiple Aspects (unspecified)’ option may also be relevant for projects referencing legacy data on collections that are inaccessible, which may have less specificity. Unsure if that is something we are considering at the moment, but as someone who has worked with legacy data frequently, I can see it being valuable.

**Comment by HannahLiedl** [comment]
Hi Sylvia,

I'm sorry to hear you are running into a few difficulties and I agree that these are issues.
I think everything that is coded in the pathology form should be described in the notes. It might not end up in the report, but it should be in the notes. The "multiple aspects" option in the database was introduced because we couldn't enter multiple values into the database. So while the database says "multiple aspects", the notes file should then specificy what aspects are affected. There might also be some issues with this in the earlier recordings from last year, since this was introduced at a later stage (September apparently). I can't quite remember how I solved the issue last summer...

If you think, that  an "unspecified" option will help, I agree we should add this. It shouldn't be used as much (but would also be helpful for fibula diaphysis fragments for example where it can be more tricky in general), and the notes should be as specific as possible. If there is bone formation on the medial and lateral aspect of the tibia, this should be specified in the notes and not just called "Multiple surfaces" (even though this is what it will say in the database). I can see if I can make a note in the pathology scoring key for this, too, if we agree on it.

**Comment by sacheever** [comment]
@HannahLiedl, I think it would be valuable to have as an ‘emergency’ option. I agree it should ONLY be used in the rare case where the ‘multiple surfaces’ option is unelaborated on. I don’t anticipate this being a very consistent problem. But having the unspecified option in those rare cases allows data editors to complete path entry for those individuals instead of having to stop, contact original observers, wait for clarification (which may not even be possible if no one in Athens has time to revisit the individual, or everyone has left when the data entry is occurring), and leave the entry half finished. Having this option will also make it very easy to query a list of path observations in the database that may need to be revisited the next time someone is able (you would be able to filter based on the ‘unspecified’ option and know exactly what bones and individuals oversight on exact location occurred during past phases of data collection).

**Comment by cuboideum** [comment]
> Having this option will also make it very easy to query a list of path observations in the database that may need to be revisited the next time someone is able (you would be able to filter based on the ‘unspecified’ option and know exactly what bones and individuals oversight on exact location occurred during past phases of data collection).

I agree that you should try to obtain a similar level of detail with all individuals and that it would be best to re-investigate individuals for which the information is missing.

You will have to make a decision among yourselves, though.

**Comment by HannahLiedl** [comment]
I think Sylvia's suggestion would be a good addition to the database. 
@JEB13 do you agree and should we make this change?

**Comment by cuboideum** [comment]
During a meeting between the Phaleron Bioarchaeological Project and the RDFBones/AnthroGraph workgroup on 30 August 2022 it was decided that an option 'multiple surfaces (unspecified)' should be added to enter existing data from spreadsheets. This option, however, should not be used for recording new datasets where the affected surfaces shall be specified by multiple entries.

@cuboideum is charged with making the necessary changes to the ontology.

@HannahLiedl is charged with updating the Phaleron scoring key and making sure that the option 'multiple surfaces' is documented as a legacy item.

**Comment by HannahLiedl** [comment]
Scoring key is updated

**Comment by cuboideum** [comment]
We still need to add the 'multiple surfaces' label to the ontology.

**Comment by cuboideum** [comment]
This issue was discussed again at a meeting of the RDFBones/AnthroGraph workgroup on 14 March 2023. @zarquon42b strongly opposed the decision taken on 30 August 2022 as it would implement insecurities of data collection into the data standard.

Probably we should bring this up again at a future meeting.

**Comment by cuboideum** [comment]
@hayesleigh and @cuboideum discussed this issue in a video cnfernce on 10 August 2023. They agreed that the category label 'multiple surfaces' was deprecated and should not appear in the AnthroGraph user interface. It was, therefore, decided to close the issue.
