### ISSUE TITLE
Note boxes for skeletal inventory

### ISSUE THREAD

**Issue by eprevedo** [RDFBones/RDFBonesPhaleron#30]
Please add note boxes (for text).
Boxes for skeletal inventory: these should follow the anatomical regions as defined previously (e.g. taphonomy regions) plus one general notes box for the whole inventory
Notes boxes should be optional and do not have to be filled out necessarily for each region.
We would follow this pattern for the paleopath as well.

**Comment by cuboideum** [comment]
I think we should discuss note boxes for each module separately as requirements and structures might vary.

I have taken the liberty to rename this issue so that it covers skeletal inventory exclusively. Specifications for this are contained in the opening comment.

For the palaeopathology module, I have created issue #31.

**Comment by cuboideum** [comment]
Consider if it might make sense for you to distinguish different kinds of comments, e.g. notes on the conditions under which observations or measurements were made, on qualities of the skeletal material affecting outcome and issues of conservation. This might be helpful if you plan to compile a catalogue or report from text blocks stored in the the database.

**Comment by cuboideum** [comment]
Decisions concerning note boxes were taken at some point but went undocumented. In its current state, the code reflects these decisions.
