### ISSUE TITLE
Clarification of localisation items

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#33]
The version of 23 September 2021 of the palaeopathology template includes two systems of localising observations on anatomical regions of interest:

1. '**Within Bone Location**' describes the aspect of a skeletal element on which an observation is made.
2. '**Bone Addition Location**', '**Bone Loss Location**' and (allegedly) '**Mixed lesion Location**' describe a location within the anatomical structure of a bone organ.

'Bone Addition Location' and 'Bone Loss Location' have the same category scheme and so does, most likely, 'Mixed lesion Location' (cf. #32 ). In terms of data modelling, one identical categorical label set should be created to be referenced by three different measurement data. This set needs a telling name.

I suggest the following naming conventions:

1. Change the name of 'Within Bone Location' to 'Aspect of skeletal element' as proposed in #22.
2. Use one set of categorical labels for 'Bone Addition Location', 'Bone Loss Location' and 'Mixed lesion Location'. I would say that, here, 'Within Bone Location' would be an apt title as it refers to the internal structure of bone organs. However, this might be too confusing if earlier versions of the template are in use. What about 'Location Within Bone Structure'?

@JEB13, @eprevedo, @HannahLiedl, @JessHotaling and @hayesleigh, please discuss and post results here.

**Comment by HannahLiedl** [comment]
Yes, mixed location should follow the same as bone addition and bone loss.

I believe we already agreed on the "aspect of skeletal element" somewhere? I'm afraid it was not translated into the template and key. I was focused on the mixed lesion. I don't know if makes sense to change it in the template (again)... @hayesleigh , what would you prefer as you are the one recording now?

I agree with you, I would not use "within bone location" for the "location", since we have used it the other way around for a long time now. That could become very confusing when transfering data and for recording now to make that switch. I personally like "location within bone structure".

**Comment by cuboideum** [comment]
> I believe we already agreed on the "aspect of skeletal element" somewhere?

Issue #22 is still unresolved.

**Comment by JEB13** [comment]
Let's discuss on Monday.  I think we can make the change to "aspect" now without causing too much anxiety.  I could go with "Location within Bone Structure."   I see the issue.

**Comment by cuboideum** [comment]
Fixed with commit https://github.com/RDFBones/Phaleron-Pathologies/commit/46cdf8661327e01750720922e653340898c73bb0.
