### ISSUE TITLE
'Fracture Type': Categories

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBonesPhaleron#39]
The version of 23 September of the palaeopathology scoring key defines the data item 'Fracture Type' on pages eleven and twelve. The category denominated with the numeric code 0 is called 'Unknown or Unobservable'.

This definition brakes with the scheme introduced with the other items where 'unknown' and 'unobservable' are coded as 9 (see also issue #38).

'Fracture Type' only applies if the lesion under observation has been classified as 'present' in data item 'Fracture Presence'. For the spreadsheet template, an option 'Not applicable' would be needed for non-fracture lesions. Habitually, this option would be coded as 0. For the RDFBones implementation, 'Fracture Type' can be made dependent on the data item 'Fracture Presence'.

I suggest to drop category 0 and introduce a new category denominated with the numeric code 9 and called 'Unknown, unobservable'.

@JEB13, @eprevedo, @HannahLiedl, @JessHotaling and @hayesleigh, what do you think?

**Comment by HannahLiedl** [comment]
I think the issue with this might have been that we have more than 9 options to select here (also in #40 ) so "unknown/unobservable" would be somewhere in the middle of the list. But I do understand that it might be confusing to change the numeric code just for trauma.
I'm wondering now if the numeric code will show up when using the database or if this is only in the background and on our side the numeric code will be mainly used for transferring collected data into the database? Obviously, I don't actually know anything about how the programming works, so I can base this only on how I think this will be used in the end. If changing the numeric code makes more sense on your end, we should consider it. Or what do other people think? I'm afraid it will become more and more confusing to transfer the trauma data since this has been changed so many times now...

**Comment by cuboideum** [comment]
> I'm wondering now if the numeric code will show up when using the database or if this is only in the background and on our side the numeric code will be mainly used for transferring collected data into the database?

The numeric code is not relevant for data modelling or building data entry forms. It is only significant for your coding system - and certainly for relational databases that might be implementing the standard.

**Comment by cuboideum** [comment]
> I think the issue with this might have been that we have more than 9 options to select

Yes, this is a problem. It would have been more cautious to use code 99 for the 'unknown' (or NULL) option. But now that the codes have already been used, changing everything is probably difficult and potentially misleading.

Even if there are more than nine options, these do not necessarily need to use code 9 but higher numbers, instead.

The decision on how coherence of numeric codes is best achieved is entirely on your side.

**Comment by HannahLiedl** [comment]
No, it makes sense to have it in a coherent way. Changing 9 to 99 is probably not an option anymore at this stage. Let's see what the others are saying, but I see your point on coherence.

**Comment by cuboideum** [comment]
Fixed with commit https://github.com/RDFBones/Phaleron-Pathologies/commit/c36ff51c8d050a2f888be467992aaacf41560475.
