### ISSUE TITLE
Unsided, grouped elements (in this case ribs) do not register as possible ROIs for Paleopath Recording

### ISSUE THREAD

**Issue by sacheever** [RDFBones/RDFBonesPhaleron#73]
**In what module does the bug occur?**
Paleopathology
 
**Describe the bug**
In the Excel data sheets, there is the opportunity to record pathology for clusters of grouped, unsided fragments from particular elements and regions of the body (In the particular case I am working with, IV_402, there are a number of unsided, grouped rib bodies that exhibit pathology that has been coded in the data sheet and described in the report). However, even when numeric values are accurately recorded in the corresponding 'unsided, grouped' fragment categories in the inventory, these fragment clusters do not appear as potential ROIs in the paleopath module. 

**To Reproduce**
1. Go to the skeletal paleopathology entry for IV_402
2. Click on the Thorax Tab and go to the 'Periosteal Bone Addition to the Ribs' entry that has already been created
3. Click on the ROI list
4. See error - No ROIs available for selection (even though 3 unsided rib fragments are correctly recorded in the IV_402 skeletal inventory). 

**Expected behavior**
I expect an option of 'Unsided Ribs Grouped Body' (the name of the category available in the excel spreadsheet), to be available for path recording, as is available in the excel sheet.

**Comment by cuboideum** [comment]
In a meeting between the Phaleron Bioarchaeological Project and the RDFBones/AnthroGraph work group on 9 August 2022 it was decided that the most important information for data analysis is the information that a certain condition occurs with a skeleton. The more detailed information about how many fragments or elements are or might be affected is too complex to be captured in data items for structured information and still provide data that can be reasonably analysed. It should be recorded in a comments section relating to the paleopathology section.

Currently, only some pathology sections have comment fields. In order to provide uniform opportunity to record detailed information about pathological observations on grouped ROIs all sections need to have comment fields.

**Comment by cuboideum** [comment]
Fixed in pull request https://github.com/AnthroGraph/PBP-App/pull/48. Once that pull request is reviewed and merged this issue can be closed.

**Comment by cuboideum** [comment]
@zarquon42b: Please update productivity instance and close this issue.

**Comment by cuboideum** [comment]
The production instance is up to date and provides the functionality.
