### ISSUE TITLE
Alveolar resorption options within dental pathology incorrect 

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#77]
Hello, the options for alveolar resorption within the dental pathology module are incorrect. Currently the options read : ThreetoFiveMillimeters, Alveolar Resorption, 2-3mm, Unobservable, Absent, Majority of tooth root exposed, and complete. (Picture shown below). 

![image](https://user-images.githubusercontent.com/90316213/200622780-59c8814d-e783-412d-9c29-06413bc31ae5.png)

They should read: 

Absent, Slight (2-3 mm), Moderate (3-5mm), Severe (majority of root exposed), Complete (tooth evulsed, alveoli completely obliterated), and Unobservable. Picture below. 

![image](https://user-images.githubusercontent.com/90316213/200623818-f5b608f3-c5d4-4354-9cea-503b94bb61af.png)

**Comment by cuboideum** [comment]
Fixed with pull request https://github.com/RDFBones/Phaleron-DentalPathologies/commit/1cd761425da9cd8afb63be6b69212bb21eb4e734. The changes are also included in the Phaleron App Ontology since commit https://github.com/AnthroGraph/Phaleron-AppOntology/commit/89c74ba722ba00c7969451c909d4f14b6ab8a0d4.

The fix has been tested with a development instance of AnthroGraph. @zarquon42b: Please update production instance and/or confirm proper functionality there.

**Comment by hayesleigh** [comment]
Checked and functions properly now, thank you!
