### ISSUE TITLE
Sex Estimation module general information tab needed

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#95]
**Is your feature request related to a problem? Please describe.**
There is currently no area for inputting notes or observer/data editor names/dates. 
This feature is necessary for putting in the justification of the observer on the sex estimate.

**Describe the solution you'd like**
Would like a general tab as we have in the other modules with a notes section as well as be able to input who the observer is and when they observed the individual.

**Comment by 15E601** [comment]
I have proposed an implementation in [Pull-request 63](https://github.com/AnthroGraph/PBP-App/pull/63)
This will not have its own tab like it does in the skeletal inventory since the Sex-estimation module is all on one page, and I thought it easiest to keep it that way. However, tabs could be added if preferred.

**Comment by cuboideum** [comment]
@15E601: Pull request https://github.com/AnthroGraph/PBP-App/pull/63 has been merged. Can this issue be closed?

**Comment by 15E601** [comment]
Both comment and editor events are seeing use and there appear to be no issues. A separated tab was not requested. Closing this issue.
